// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Rl7v5CTir4Bw5ATfqOXlasgUkRmaXG8',
    appId: '1:986011320631:web:24e11ddd01cb1e58049ab2',
    messagingSenderId: '986011320631',
    projectId: 'govolt-5dd50',
    authDomain: 'govolt-5dd50.firebaseapp.com',
    storageBucket: 'govolt-5dd50.appspot.com',
    measurementId: 'G-K940PMKC6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4CGpMmBrtiQxcSaYDwywSWVdUkqIN_5g',
    databaseURL:
        "https://govolt-47ea1-default-rtdb.europe-west1.firebasedatabase.app",
    appId: '1:699229746495:android:93429fb1e4a3cdf1360f8a',
    messagingSenderId: '986011320631',
    projectId: 'govolt-47ea1',
    storageBucket: 'govolt-47ea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Z8V8hdZu-kK9LuVX17CtC8o2c1ddcJM',
    appId: '1:986011320631:ios:003b9b80d478cd38049ab2',
    messagingSenderId: '986011320631',
    projectId: 'govolt-5dd50',
    storageBucket: 'govolt-5dd50.appspot.com',
    iosBundleId: 'com.example.govoltfrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Z8V8hdZu-kK9LuVX17CtC8o2c1ddcJM',
    appId: '1:986011320631:ios:f4342d0c9332df51049ab2',
    messagingSenderId: '986011320631',
    projectId: 'govolt-5dd50',
    storageBucket: 'govolt-5dd50.appspot.com',
    iosBundleId: 'com.example.govoltfrontend.RunnerTests',
  );
}
